name: Benchmark on GPU Server

on:
  workflow_dispatch:

jobs:
  release-windows:
    runs-on: [self-hosted, windows, x64, gpu]
    name: Benchmark on self-hosted GPU runner
    steps:
      #checkout code
      - name: Checkout code
        id: checkout_code
        uses: actions/checkout@v4
  
      # Not needed, already set in path
      #Locate MSBuild.exe and add to PATH
      # - name: Add MSBuild to PATH
      #   id: setup_msbuild
      #   uses: microsoft/setup-msbuild@v2
      #   with:
      #     msbuild-architecture: x64
         
      #Run MSBuild Release
      - name: Run MSBuild Release
        id: run_msbuild_release
        working-directory: .\
        run: msbuild.exe .\ -t:VulOptiSim -property:Configuration=Release -property:Platform=x64
  
      #Upload release build as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: windows-release-artifact
          path: x64/Release

      #Copy the assest folders into the release folder
      - name: Copy assets to x64/Release
        shell: cmd
        run: |
          mkdir x64\
          xcopy /E /I /Y models x64\models
          xcopy /E /I /Y shaders x64\shaders
          xcopy /E /I /Y textures x64\textures

      #Run project
      - name: Run project
        id: run_project
        working-directory: x64\Release
        shell: cmd
        run: VulOptiSim.exe
